# Generated by inspectdb
# DO NOT EDIT THIS FILE DIRECTLY
import decimal
from unittest import result
import json
from Django_Shop.settings import IMAGE_URL

from django.db import models

class Goods(models.Model):
    type_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    sku_id = models.CharField(max_length=255, blank=True, null=True)
    target_url = models.CharField(max_length=255, blank=True, null=True)
    jd_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    p_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    image = models.CharField(max_length=255, blank=True, null=True)
    shop_name = models.CharField(max_length=255, blank=True, null=True)
    shop_id = models.IntegerField(blank=True, null=True)
    spu_id = models.CharField(max_length=255, blank=True, null=True)
    mk_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    vender_id = models.IntegerField(blank=True, null=True)
    find = models.IntegerField(blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    # 序列化
    def __str__(self):
        result = {}
        result['type_id'] = self.type_id
        result['name'] = self.name
        result['sku_id'] = self.sku_id
        result['target_url'] = self.target_url
        result['jd_price'] = self.jd_price
        result['p_price'] = self.p_price

        result['image'] = IMAGE_URL + self.image
        result['shop_name'] = self.shop_name
        result['shop_id'] = self.shop_id
        result['spu_id'] = self.spu_id
        result['mk_price'] = self.mk_price
        result['vender_id'] = self.vender_id
        result['find'] = self.find
        return json.dumps(result,cls=DecimalEncoder , ensure_ascii=False)


    class Meta:
        managed = False
        db_table = 'goods'

# 数据库里面的价格类型是decimal，要做类型转换到python
class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return float(o)