# Generated by inspectdb
# DO NOT EDIT THIS FILE DIRECTLY

from django.db import models
from django.utils import timezone


from django.db import models
class UserAddress(models.Model):
    id = models.IntegerField(primary_key=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    signer_name = models.CharField(max_length=255, blank=True, null=True)
    telphone = models.CharField(max_length=255, blank=True, null=True)
    signer_address = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    default = models.IntegerField(blank=True, null=True)
    create_time = models.DateTimeField(default=timezone.now)
    class Meta:
        managed = False
        db_table = 'user_address'

