# Generated by inspectdb
# DO NOT EDIT THIS FILE DIRECTLY

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
import hashlib


class UserManager(BaseUserManager):
    """自定义用户管理器，支持email作为用户名"""

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('邮箱必须填写')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)

        # MD5加密密码
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('超级用户必须设置 is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('超级用户必须设置 is_superuser=True')

        return self.create_user(email, password, **extra_fields)


# class User(models.Model):
class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=255, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    mobile = models.CharField(max_length=255, blank=True, null=True)
    gender = models.IntegerField(choices=((0, '女'), (1, '男'), (2, '保密')), blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True, unique=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)

    # 管理员相关字段
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(null=True, blank=True)
    # 指定使用email作为登录字段
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']  # 使用createsuperuser命令时需要的字段
    # 指定自定义管理器
    objects = UserManager()

    def __str__(self):
        return self.email or self.name or '未命名用户'

    def set_password(self, raw_password):
        """使用MD5加密密码"""
        if raw_password:
            # MD5加密
            md5_hash = hashlib.md5(raw_password.encode('utf-8')).hexdigest()
            self.password = md5_hash

    def check_password(self, raw_password):
        """验证MD5密码"""
        if not raw_password or not self.password:
            return False
        return self.password == hashlib.md5(raw_password.encode('utf-8')).hexdigest()

    def get_full_name(self):
        return self.name or self.email

    def get_short_name(self):
        return self.name or self.email

    class Meta:
        managed = False
        db_table = 'user'


class UserAddress(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses',
    #                          db_column='user_id', blank=True,null=True)

    email = models.CharField(max_length=255, blank=True, null=True)
    signer_name = models.CharField(max_length=255, blank=True, null=True)
    telphone = models.CharField(max_length=255, blank=True, null=True)
    signer_address = models.CharField(max_length=255, blank=True, null=True)
    district = models.CharField(max_length=255, blank=True, null=True)
    default = models.IntegerField(blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'user_address'

