# create_models.py
import sys
import os
import django

# 设置 Django 环境
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Django_Shop.settings')
django.setup()

from django.core.management import call_command


def generate_models():
    tables = {
        # '表名': 'apps/应用名/models.py',

        # 'goods': 'apps/goods/models.py',
        # 'shopping_cart': 'apps/cart/models.py',


        # 'order': 'apps/order/models.py',
        # 'order_goods': 'apps/order/models.py',

        'user_address': 'apps/address/models.py',

        # 'user_address': 'apps/user/models.py',  # 追加到 user 应用
        # 'main_menu': 'apps/goods/models.py',  # 追加到 goods 应用
        # 'sub_menu': 'apps/goods/models.py',  # 追加到 goods 应用
    }

    # 按应用分组生成
    app_files = {}
    for table, filepath in tables.items():
        if filepath not in app_files:
            app_files[filepath] = []
        app_files[filepath].append(table)

    # 为每个应用生成模型文件
    for filepath, table_list in app_files.items():
        print(f"Generating models for {table_list} -> {filepath}")

        # 确保目录存在
        os.makedirs(os.path.dirname(filepath), exist_ok=True)

        with open(filepath, 'w', encoding='utf-8') as f:
            # 写入文件头
            f.write('# Generated by inspectdb\n')
            f.write('# DO NOT EDIT THIS FILE DIRECTLY\n\n')
            f.write('from django.db import models\n\n\n')

            # 为每个表生成模型
            for table in table_list:
                print(f"  Processing table: {table}")

                # 捕获 inspectdb 输出
                from io import StringIO
                output = StringIO()
                call_command('inspectdb', '--database', 'default', table, stdout=output)
                output.seek(0)
                model_code = output.read()

                # 清理输出（移除自动生成的注释等）
                lines = model_code.split('\n')
                cleaned_lines = []
                for line in lines:
                    # 保留有用的内容
                    if line.strip() and not line.strip().startswith('#') or 'class' in line:
                        cleaned_lines.append(line)

                # 写入清理后的代码
                f.write('\n'.join(cleaned_lines))
                f.write('\n\n')

        print(f"✓ Successfully generated: {filepath}")


if __name__ == '__main__':
    generate_models()