[uwsgi]
chdir=/workspace/Django_Shop/
module=Django_Shop.wsgi:application
master=True
pidfile=/workspace/Django_Shop/projext-master.pid
vacuum=True
max-requests=5000
daemonize=/workspace/Django_Shop/log/uwsgi/Django_Shop.log
http-socket= :8000
static-map=/static/product_images=/workspace/Django_Shop/static/product_images